---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: argo-apps-default

namespace: argocd

# Reference the base
resources:
  - ../../base
  - prometheus.yaml
  - grafana.yaml
  - loki.yaml
