---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-subnet-router
  namespace: tailscale-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-subnet-router
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-subnet-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-subnet-router
subjects:
- kind: ServiceAccount
  name: tailscale-subnet-router
  namespace: tailscale-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale-system
  labels:
    app: tailscale-subnet-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      serviceAccountName: tailscale-subnet-router
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_AUTHKEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: authkey
        - name: TS_HOSTNAME
          value: "gke-subnet-router"
        - name: TS_STATE_DIR
          value: /var/lib/tailscale
        - name: TS_ROUTES
          value: "10.10.0.0/24,10.11.0.0/16,10.12.0.0/16"
        - name: TS_USERSPACE
          value: "false"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
          privileged: true
        volumeMounts:
        - name: tailscale-state
          mountPath: /var/lib/tailscale
        - name: dev-net-tun
          mountPath: /dev/net/tun
      volumes:
      - name: tailscale-state
        hostPath:
          path: /var/lib/tailscale
          type: DirectoryOrCreate
      - name: dev-net-tun
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists