---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: tailscale-operator

namespace: tailscale

resources:
  - tailscale-operator.yaml
  - operator-oauth-secret.yaml

patchesStrategicMerge:
  - operator-no-tags-patch.yaml
