---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: kvbikkeLUd11CNTRL
  client_secret: tskey-client-kvbikkeLUd11CNTRL-rKs5UWXxa6dFZFNYC1YC6dc1EmJLyiFmQ
