---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: k4t7L2oqEX11CNTRL
  client_secret: tskey-client-k4t7L2oqEX11CNTRL-isssSj89RjFwym9vp9zejFShm1bYnng4
