---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: tailscale
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: OPERATOR_INITIAL_TAGS
          $patch: delete
        - name: PROXY_TAGS
          $patch: delete
